import type { Surah, Juz } from '@/types';

const makkah = { en: 'Makkah', ar: 'مكية', fr: 'Mecque', es: 'La Meca', id: 'Mekkah', ru: 'Мекка', ur: 'مکی' };
const madinah = { en: 'Madinah', ar: 'مدنية', fr: 'Médine', es: 'Medina', id: 'Madinah', ru: 'Медина', ur: 'مدنی' };


export const surahs: Surah[] = [
    { id: 1, name: 'Al-Fatihah', arabicName: 'ٱلْفَاتِحَة', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 7, juz: [1] },
    { id: 2, name: 'Al-Baqarah', arabicName: 'ٱلْبَقَرَة', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 286, juz: [1, 2, 3] },
    { id: 3, name: 'Ali Imran', arabicName: 'آلِ عِمْرَان', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 200, juz: [3, 4] },
    { id: 4, name: 'An-Nisa', arabicName: 'ٱلنِّسَاء', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 176, juz: [4, 5, 6] },
    { id: 5, name: 'Al-Maidah', arabicName: 'ٱلْمَائِدَة', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 120, juz: [6, 7] },
    { id: 6, name: 'Al-Anam', arabicName: 'ٱلْأَنْعَام', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 165, juz: [7, 8] },
    { id: 7, name: 'Al-Araf', arabicName: 'ٱلْأَعْرَاف', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 206, juz: [8, 9] },
    { id: 8, name: 'Al-Anfal', arabicName: 'ٱلْأَنْفَال', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 75, juz: [9, 10] },
    { id: 9, name: 'At-Tawbah', arabicName: 'ٱلتَّوْبَة', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 129, juz: [10, 11] },
    { id: 10, name: 'Yunus', arabicName: 'يُونُس', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 109, juz: [11] },
    { id: 11, name: 'Hud', arabicName: 'هُود', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 123, juz: [11, 12] },
    { id: 12, name: 'Yusuf', arabicName: 'يُوسُف', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 111, juz: [12, 13] },
    { id: 13, name: 'Ar-Rad', arabicName: 'ٱلرَّعْد', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 43, juz: [13] },
    { id: 14, name: 'Ibrahim', arabicName: 'إِبْرَاهِيم', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 52, juz: [13] },
    { id: 15, name: 'Al-Hijr', arabicName: 'ٱلْحِجْر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 99, juz: [14] },
    { id: 16, name: 'An-Nahl', arabicName: 'ٱلنَّحْل', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 128, juz: [14] },
    { id: 17, name: 'Al-Isra', arabicName: 'ٱلْإِسْرَاء', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 111, juz: [15] },
    { id: 18, name: 'Al-Kahf', arabicName: 'ٱلْكَهْف', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 110, juz: [15, 16] },
    { id: 19, name: 'Maryam', arabicName: 'مَرْيَم', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 98, juz: [16] },
    { id: 20, name: 'Taha', arabicName: 'طه', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 135, juz: [16] },
    { id: 21, name: 'Al-Anbiya', arabicName: 'ٱلْأَنْبِيَاء', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 112, juz: [17] },
    { id: 22, name: 'Al-Hajj', arabicName: 'ٱلْحَجّ', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 78, juz: [17] },
    { id: 23, name: 'Al-Muminun', arabicName: 'ٱلْمُؤْمِنُون', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 118, juz: [18] },
    { id: 24, name: 'An-Nur', arabicName: 'ٱلنُّور', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 64, juz: [18] },
    { id: 25, name: 'Al-Furqan', arabicName: 'ٱلْفُرْقَان', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 77, juz: [18, 19] },
    { id: 26, name: 'Ash-Shuara', arabicName: 'ٱلشُّعَرَاء', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 227, juz: [19] },
    { id: 27, name: 'An-Naml', arabicName: 'ٱلنَّمْل', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 93, juz: [19, 20] },
    { id: 28, name: 'Al-Qasas', arabicName: 'ٱلْقَصَص', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 88, juz: [20] },
    { id: 29, name: 'Al-Ankabut', arabicName: 'ٱلْعَنْكَبُوت', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 69, juz: [20, 21] },
    { id: 30, name: 'Ar-Rum', arabicName: 'ٱلرُّوم', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 60, juz: [21] },
    { id: 31, name: 'Luqman', arabicName: 'لُقْمَان', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 34, juz: [21] },
    { id: 32, name: 'As-Sajdah', arabicName: 'ٱلسَّجْدَة', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 30, juz: [21] },
    { id: 33, name: 'Al-Ahzab', arabicName: 'ٱلْأَحْزَاب', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 73, juz: [21, 22] },
    { id: 34, name: 'Saba', arabicName: 'سَبَأ', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 54, juz: [22] },
    { id: 35, name: 'Fatir', arabicName: 'فَاطِر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 45, juz: [22] },
    { id: 36, name: 'Ya-Sin', arabicName: 'يس', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 83, juz: [22, 23] },
    { id: 37, name: 'As-Saffat', arabicName: 'ٱلصَّافَّات', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 182, juz: [23] },
    { id: 38, name: 'Sad', arabicName: 'ص', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 88, juz: [23] },
    { id: 39, name: 'Az-Zumar', arabicName: 'ٱلزُّمَر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 75, juz: [23, 24] },
    { id: 40, name: 'Ghafir', arabicName: 'غَافِر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 85, juz: [24] },
    { id: 41, name: 'Fussilat', arabicName: 'فُصِّلَت', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 54, juz: [24] },
    { id: 42, name: 'Ash-Shura', arabicName: 'ٱلشُّورىٰ', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 53, juz: [25] },
    { id: 43, name: 'Az-Zukhruf', arabicName: 'ٱلزُّخْرُف', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 89, juz: [25] },
    { id: 44, name: 'Ad-Dukhan', arabicName: 'ٱلدُّخَان', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 59, juz: [25] },
    { id: 45, name: 'Al-Jathiyah', arabicName: 'ٱلْجَاثِيَة', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 37, juz: [25] },
    { id: 46, name: 'Al-Ahqaf', arabicName: 'ٱلْأَحْقَاف', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 35, juz: [26] },
    { id: 47, name: 'Muhammad', arabicName: 'مُحَمَّد', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 38, juz: [26] },
    { id: 48, name: 'Al-Fath', arabicName: 'ٱلْفَتْح', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 29, juz: [26] },
    { id: 49, name: 'Al-Hujurat', arabicName: 'ٱلْحُجُرَات', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 18, juz: [26] },
    { id: 50, name: 'Qaf', arabicName: 'ق', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 45, juz: [26] },
    { id: 51, name: 'Adh-Dhariyat', arabicName: 'ٱلذَّارِيَات', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 60, juz: [26, 27] },
    { id: 52, name: 'At-Tur', arabicName: 'ٱلطُّور', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 49, juz: [27] },
    { id: 53, name: 'An-Najm', arabicName: 'ٱلنَّجْم', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 62, juz: [27] },
    { id: 54, name: 'Al-Qamar', arabicName: 'ٱلْقَمَر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 55, juz: [27] },
    { id: 55, name: 'Ar-Rahman', arabicName: 'ٱلرَّحْمَٰن', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 78, juz: [27] },
    { id: 56, name: 'Al-Waqiah', arabicName: 'ٱلْوَاقِعَة', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 96, juz: [27] },
    { id: 57, name: 'Al-Hadid', arabicName: 'ٱلْحَدِيد', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 29, juz: [27] },
    { id: 58, name: 'Al-Mujadila', arabicName: 'ٱلْمُجَادِلَة', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 22, juz: [28] },
    { id: 59, name: 'Al-Hashr', arabicName: 'ٱلْحَشْر', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 24, juz: [28] },
    { id: 60, name: 'Al-Mumtahanah', arabicName: 'ٱلْمُمْتَحَنَة', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 13, juz: [28] },
    { id: 61, name: 'As-Saff', arabicName: 'ٱلصَّفّ', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 14, juz: [28] },
    { id: 62, name: 'Al-Jumuah', arabicName: 'ٱلْجُمُعَة', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 11, juz: [28] },
    { id: 63, name: 'Al-Munafiqun', arabicName: 'ٱلْمُنَافِقُون', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 11, juz: [28] },
    { id: 64, name: 'At-Taghabun', arabicName: 'ٱلتَّغَابُن', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 18, juz: [28] },
    { id: 65, name: 'At-Talaq', arabicName: 'ٱلطَّلَاق', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 12, juz: [28] },
    { id: 66, name: 'At-Tahrim', arabicName: 'ٱلتَّحْرِيم', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 12, juz: [28] },
    { id: 67, name: 'Al-Mulk', arabicName: 'ٱلْمُلْك', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 30, juz: [29] },
    { id: 68, name: 'Al-Qalam', arabicName: 'ٱلْقَلَم', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 52, juz: [29] },
    { id: 69, name: 'Al-Haqqah', arabicName: 'ٱلْحَاقَّة', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 52, juz: [29] },
    { id: 70, name: 'Al-Maarij', arabicName: 'ٱلْمَعَارِج', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 44, juz: [29] },
    { id: 71, name: 'Nuh', arabicName: 'نُوح', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 28, juz: [29] },
    { id: 72, name: 'Al-Jinn', arabicName: 'ٱلْجِنّ', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 28, juz: [29] },
    { id: 73, name: 'Al-Muzzammil', arabicName: 'ٱلْمُزَّمِّل', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 20, juz: [29] },
    { id: 74, name: 'Al-Muddaththir', arabicName: 'ٱلْمُدَّثِّر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 56, juz: [29] },
    { id: 75, name: 'Al-Qiyamah', arabicName: 'ٱلْقِيَامَة', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 40, juz: [29] },
    { id: 76, name: 'Al-Insan', arabicName: 'ٱلْإِنْسَان', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 31, juz: [29] },
    { id: 77, name: 'Al-Mursalat', arabicName: 'ٱلْمُرْسَلَات', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 50, juz: [29] },
    { id: 78, name: 'An-Naba', arabicName: 'ٱلنَّبَأ', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 40, juz: [30] },
    { id: 79, name: 'An-Naziat', arabicName: 'ٱلنَّازِعَات', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 46, juz: [30] },
    { id: 80, name: 'Abasa', arabicName: 'عَبَسَ', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 42, juz: [30] },
    { id: 81, name: 'At-Takwir', arabicName: 'ٱلتَّكْوِير', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 29, juz: [30] },
    { id: 82, name: 'Al-Infitar', arabicName: 'ٱلْإِنْفِطَار', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 19, juz: [30] },
    { id: 83, name: 'Al-Mutaffifin', arabicName: 'ٱلْمُطَفِّفِين', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 36, juz: [30] },
    { id: 84, name: 'Al-Inshiqaq', arabicName: 'ٱلْإِنْشِقَاق', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 25, juz: [30] },
    { id: 85, name: 'Al-Buruj', arabicName: 'ٱلْبُرُوج', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 22, juz: [30] },
    { id: 86, name: 'At-Tariq', arabicName: 'ٱلطَّارِق', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 17, juz: [30] },
    { id: 87, name: 'Al-Ala', arabicName: 'ٱلْأَعْلَىٰ', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 19, juz: [30] },
    { id: 88, name: 'Al-Ghashiyah', arabicName: 'ٱلْغَاشِيَة', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 26, juz: [30] },
    { id: 89, name: 'Al-Fajr', arabicName: 'ٱلْفَجْر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 30, juz: [30] },
    { id: 90, name: 'Al-Balad', arabicName: 'ٱلْبَلَد', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 20, juz: [30] },
    { id: 91, name: 'Ash-Shams', arabicName: 'ٱلشَّمْس', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 15, juz: [30] },
    { id: 92, name: 'Al-Layl', arabicName: 'ٱللَّيْل', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 21, juz: [30] },
    { id: 93, name: 'Ad-Duha', arabicName: 'ٱلضُّحَىٰ', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 11, juz: [30] },
    { id: 94, name: 'Ash-Sharh', arabicName: 'ٱلشَّرْح', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 8, juz: [30] },
    { id: 95, name: 'At-Tin', arabicName: 'ٱلتِّين', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 8, juz: [30] },
    { id: 96, name: 'Al-Alaq', arabicName: 'ٱلْعَلَق', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 19, juz: [30] },
    { id: 97, name: 'Al-Qadr', arabicName: 'ٱلْقَدْر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 5, juz: [30] },
    { id: 98, name: 'Al-Bayyinah', arabicName: 'ٱلْبَيِّنَة', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 8, juz: [30] },
    { id: 99, name: 'Az-Zalzalah', arabicName: 'ٱلزَّلْزَلَة', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 8, juz: [30] },
    { id: 100, name: 'Al-Adiyat', arabicName: 'ٱلْعَادِيَات', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 11, juz: [30] },
    { id: 101, name: 'Al-Qariah', arabicName: 'ٱلْقَارِعَة', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 11, juz: [30] },
    { id: 102, name: 'At-Takathur', arabicName: 'ٱلتَّكَاثُر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 8, juz: [30] },
    { id: 103, name: 'Al-Asr', arabicName: 'ٱلْعَصْر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 3, juz: [30] },
    { id: 104, name: 'Al-Humazah', arabicName: 'ٱلْهُمَزَة', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 9, juz: [30] },
    { id: 105, name: 'Al-Fil', arabicName: 'ٱلْفِيل', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 5, juz: [30] },
    { id: 106, name: 'Quraysh', arabicName: 'قُرَيْش', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 4, juz: [30] },
    { id: 107, name: 'Al-Maun', arabicName: 'ٱلْمَاعُون', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 7, juz: [30] },
    { id: 108, name: 'Al-Kawthar', arabicName: 'ٱلْكَوْثَر', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 3, juz: [30] },
    { id: 109, name: 'Al-Kafirun', arabicName: 'ٱلْكَافِرُون', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 6, juz: [30] },
    { id: 110, name: 'An-Nasr', arabicName: 'ٱلنَّصْر', revelationPlace: 'Madinah', revelationPlaceTranslations: madinah, versesCount: 3, juz: [30] },
    { id: 111, name: 'Al-Masad', arabicName: 'ٱلْمَسَد', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 5, juz: [30] },
    { id: 112, name: 'Al-Ikhlas', arabicName: 'ٱلْإِخْلَاص', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 4, juz: [30] },
    { id: 113, name: 'Al-Falaq', arabicName: 'ٱلْفَلَق', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 5, juz: [30] },
    { id: 114, name: 'An-Nas', arabicName: 'ٱلنَّاس', revelationPlace: 'Makkah', revelationPlaceTranslations: makkah, versesCount: 6, juz: [30] }
  ];

// A simplified Juz list. A more accurate mapping would be by verse.
export const juzs = Array.from({ length: 30 }, (_, i) => ({ id: i + 1, name: `Juz ${i + 1}` }));
